# Generated by Django 4.2.5 on 2023-09-23 18:10

import core.utilities
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('in_office', models.BooleanField(default=False, verbose_name='In Office')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=30, verbose_name='Middle Name')),
                ('maiden_name', models.CharField(blank=True, max_length=150, verbose_name='Maiden Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('preferred_name', models.CharField(blank=True, max_length=30, verbose_name='Preferred Name')),
                ('birth_date', models.DateField(blank=True, help_text='The date of birth is in the following format e.g.: yyyy-mm-dd.', null=True, verbose_name='Date of Birth')),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid telephone number; e.g.: "0878205058".', regex='^(0){1}([1-9]){1}([0-9]){8}$')], verbose_name='Mobile Number')),
                ('home_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid telephone number; e.g.: "0878205058".', regex='^(0){1}([1-9]){1}([0-9]){8}$')], verbose_name='Home Number')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Student Email')),
                ('show_contact_details', models.BooleanField(default=True, verbose_name='Show Contact Details')),
                ('notes', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('student_number', models.CharField(max_length=9, unique=True, verbose_name='Student Number')),
                ('personnel_type', models.PositiveIntegerField(choices=[(0, 'Student'), (1, 'Administrator')])),
                ('image', models.FileField(blank=True, null=True, upload_to=core.utilities.get_document_upload_path)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Student',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('resolved', models.BooleanField(default=False)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Submitted'), (2, 'In Review'), (3, 'Approved'), (4, 'Rejected'), (5, 'Terminated')], default=1, verbose_name='Application Status')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.personnel', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['student'],
            },
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('student',), name='application_student'),
        ),
    ]
