# Generated by Django 4.2.6 on 2023-10-19 19:24

import core.utilities
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('resolved', models.BooleanField(default=False)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Submitted'), (2, 'In Review'), (3, 'Approved'), (4, 'Rejected'), (5, 'Terminated')], default=1, verbose_name='Application Status')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.room')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['student'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('birth_date', models.DateField(blank=True, help_text='The date of birth is in the following format e.g.: yyyy-mm-dd.', null=True, verbose_name='Date of Birth')),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid telephone number; e.g.: "0878205058".', regex='^(0){1}([1-9]){1}([0-9]){8}$')], verbose_name='Mobile Number')),
                ('home_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid telephone number; e.g.: "0878205058".', regex='^(0){1}([1-9]){1}([0-9]){8}$')], verbose_name='Home Number')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Student Email')),
                ('personal_email', models.EmailField(max_length=254, verbose_name='Personal Email')),
                ('student_number', models.CharField(max_length=9, unique=True, verbose_name='Student Number')),
                ('personnel_type', models.PositiveIntegerField(choices=[(0, 'Student'), (1, 'Administrator')])),
                ('image', models.FileField(blank=True, null=True, upload_to=core.utilities.get_document_upload_path)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Student',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.application')),
                ('from_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_from_room', to='structure.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.personnel', verbose_name='Student')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_to_room', to='structure.room')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['student'],
            },
        ),
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.application')),
            ],
            options={
                'verbose_name': 'Termination',
                'verbose_name_plural': 'Terminations',
                'ordering': ['application'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.personnel', verbose_name='Student'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(fields=('student', 'application', 'from_room', 'to_room'), name='transfer_student_application_from_room_to_room'),
        ),
        migrations.AddConstraint(
            model_name='termination',
            constraint=models.UniqueConstraint(fields=('application',), name='termination_application'),
        ),
    ]
