# Generated by Django 4.2.4 on 2023-09-04 18:02

import administration.utilities
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Campus')),
                ('location', models.CharField(max_length=64, verbose_name='Location')),
                ('address', models.CharField(max_length=128, verbose_name='Address')),
                ('path', models.CharField(max_length=32, unique=True)),
                ('email_address', models.EmailField(blank=True, help_text='This is the mailing group email address for the campus.', max_length=254, null=True, verbose_name='Email Address')),
                ('image', models.FileField(blank=True, null=True, upload_to=administration.utilities.get_document_upload_path)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Residence')),
                ('image', models.FileField(blank=True, null=True, upload_to=administration.utilities.get_document_upload_path)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.campus')),
            ],
            options={
                'verbose_name': 'Residence',
                'verbose_name_plural': 'Residences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='Residence')),
                ('floor', models.IntegerField(verbose_name='Floor')),
                ('image', models.FileField(blank=True, null=True, upload_to=administration.utilities.get_document_upload_path)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.residence')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Room',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('in_office', models.BooleanField(default=False, verbose_name='In Office')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=30, verbose_name='Middle Name')),
                ('maiden_name', models.CharField(blank=True, max_length=150, verbose_name='Maiden Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('preferred_name', models.CharField(blank=True, max_length=30, verbose_name='Preferred Name')),
                ('birth_date', models.DateField(blank=True, help_text='The date of birth is in the following format e.g.: yyyy-mm-dd.', null=True, verbose_name='Date of Birth')),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid telephone number; e.g.: "0878205058".', regex='^(0){1}([1-9]){1}([0-9]){8}$')], verbose_name='Mobile Number')),
                ('home_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid telephone number; e.g.: "0878205058".', regex='^(0){1}([1-9]){1}([0-9]){8}$')], verbose_name='Home Number')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Student Email')),
                ('show_contact_details', models.BooleanField(default=True, verbose_name='Show Contact Details')),
                ('notes', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('student_number', models.CharField(max_length=9, unique=True, verbose_name='Student Number')),
                ('personnel_type', models.PositiveIntegerField(choices=[(0, 'Student'), (1, 'Administrator')])),
                ('image', models.FileField(blank=True, null=True, upload_to=administration.utilities.get_document_upload_path)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Student',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('name',), name='campus_name'),
        ),
        migrations.AddField(
            model_name='application',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.room'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.personnel', verbose_name='Student'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('residence', 'number'), name='room_residence_number'),
        ),
        migrations.AddConstraint(
            model_name='residence',
            constraint=models.UniqueConstraint(fields=('name', 'campus'), name='residence_name_campus'),
        ),
    ]
