# Generated by Django 4.2.4 on 2023-09-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Submitted'), (1, 'In Review'), (2, 'Approved'), (3, 'Rejected')], default=0, verbose_name='Application Status'),
        ),
    ]
