# Generated by Django 4.2.5 on 2023-10-14 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.application')),
                ('from_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_from_room', to='structure.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.personnel', verbose_name='Student')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_to_room', to='structure.room')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['student'],
            },
        ),
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.application')),
            ],
            options={
                'verbose_name': 'Termination',
                'verbose_name_plural': 'Terminations',
                'ordering': ['application'],
            },
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(fields=('student', 'application', 'from_room', 'to_room'), name='transfer_student_application_from_room_to_room'),
        ),
        migrations.AddConstraint(
            model_name='termination',
            constraint=models.UniqueConstraint(fields=('application',), name='termination_application'),
        ),
    ]
