# Generated by Django 4.2.4 on 2023-09-02 13:02

import administration.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=administration.utilities.get_document_upload_path),
        ),
        migrations.AddField(
            model_name='personnel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=administration.utilities.get_document_upload_path),
        ),
        migrations.AddField(
            model_name='residence',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=administration.utilities.get_document_upload_path),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=administration.utilities.get_document_upload_path),
        ),
    ]
