# Generated by Django 4.2.6 on 2023-10-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Submitted'), (2, 'Approved'), (3, 'Rejected'), (4, 'Terminated')], default=1, verbose_name='Application Status'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='student_number',
            field=models.CharField(max_length=9, null=True, unique=True, verbose_name='Student Number'),
        ),
    ]
