# Generated by Django 4.2.6 on 2023-10-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_remove_application_application_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='in_office',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='maiden_name',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='preferred_name',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='show_contact_details',
        ),
    ]
