# Generated by Django 4.2.5 on 2023-09-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['student'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('student',), name='application_student'),
        ),
    ]
