# Generated by Django 4.2.3 on 2023-07-31 20:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(help_text='This is a unique person code and is in the following format: three letters of the object type, followed by a hyphen, followed by six digits which increment. e.g.: PER-000001. This value will be auto-created.', max_length=10, unique=True, verbose_name='Person Code')),
                ('in_office', models.BooleanField(default=False, verbose_name='In Office')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=30, verbose_name='Middle Name')),
                ('maiden_name', models.CharField(blank=True, max_length=150, verbose_name='Maiden Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('preferred_name', models.CharField(blank=True, max_length=30, verbose_name='Preferred Name')),
                ('birth_date', models.DateField(blank=True, help_text='The date of birth is in the following format e.g.: yyyy-mm-dd.', null=True, verbose_name='Date of Birth')),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid telephone number; e.g.: "0878205058".', regex='^(0){1}([1-9]){1}([0-9]){8}$')], verbose_name='Mobile Number')),
                ('home_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid telephone number; e.g.: "0878205058".', regex='^(0){1}([1-9]){1}([0-9]){8}$')], verbose_name='Home Number')),
                ('personal_email_address', models.EmailField(max_length=254, verbose_name='Personal Email Address')),
                ('show_contact_details', models.BooleanField(default=True, verbose_name='Show Contact Details')),
                ('notes', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('student_number', models.CharField(max_length=9, verbose_name='Student Number')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Student',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
