# Generated by Django 4.2.3 on 2023-08-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='code',
        ),
    ]
