GOOGLE_RECAPTCHA_VERIFY_ENDPOINT = "https://www.google.com/recaptcha/api/siteverify"
GOOGLE_RECAPTCHA_SITE_KEY = "6LdGfoInAAAAAAq_Fm1jNuumifTWvWQh0Q_HLmV6"
GOOGLE_RECAPTCHA_SECRET_KEY = "6LdGfoInAAAAAOfStsPBfOzO6Y3eJPbJ31jeNGyr"
