# Generated by Django 4.2.4 on 2023-08-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'Authentication Audit',
                'verbose_name_plural': 'Authentication Audits',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='authenticationaudit',
            constraint=models.UniqueConstraint(fields=('timestamp', 'ip_address'), name='authentication_audit_timestamp_ip_address'),
        ),
    ]
